import warnings
warnings.filterwarnings("ignore")
import math

class Config:
	""" Defines parameters for the Faster R-CNN model. Default values from https://github.com/you359/Keras-FasterRCNN
	are used. """
	def __init__(self):

		self.verbose = True

		self.network = 'resnet50'

		# anchor box scales
		self.anchor_box_scales = [128, 256, 512]

		# anchor box ratios
		self.anchor_box_ratios = [[1, 1], [1./math.sqrt(2), 2./math.sqrt(2)], [2./math.sqrt(2), 1./math.sqrt(2)]]

		# placeholder for the im_size to be fed to the network
		self.im_size = None
		self.im_size_ref = 360

		# image channel-wise mean to subtract
		self.img_channel_mean = [103.939, 116.779, 123.68]
		self.img_scaling_factor = 1.0

		# maximum number of object proposals from RPN
		self.max_boxes = 20

		# number of ROIs at once
		self.num_rois = 20

		# stride at the RPN
		self.rpn_stride = 16

		# scaling the stdev
		self.std_scaling = 4.0
		self.classifier_regr_std = [8.0, 8.0, 4.0, 4.0]

		# overlaps for RPN
		self.rpn_min_overlap = 0.3
		self.rpn_max_overlap = 0.7

		# overlaps for classifier ROIs
		self.classifier_min_overlap = 0.1
		self.classifier_max_overlap = 0.5

		# placeholder for the class mapping, automatically generated by the parser
		self.class_mapping = None

		# placeholder for the model path
		self.model_path = None
